<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Product>PDF Reader</Product>
    <Authors>Jorge Zapata</Authors>
    <Copyright>Copyright (c) 2026 Jorge Zapata</Copyright>
  </PropertyGroup>
</Project>
